### ISSUE TITLE
Settings link on dashbord not working

### ISSUE THREAD

**Issue by chixxi** [Manuel83/craftbeerpi#10]
In Chrome funktioniert die "Settings Taste" nicht. Diese verweist auf den Link IP/base/#/kettle/1 bzw IP/base/#/kettle/2, angezeigt wird aber nichts:
![screenshot4](https://cloud.githubusercontent.com/assets/1770007/14768405/8f7aaaa4-0a41-11e6-9bc4-ea6f398b95a3.png)

In Firefox wird die Taste nicht dargestellt:
![screenshot2](https://cloud.githubusercontent.com/assets/1770007/14768399/82d539d6-0a41-11e6-8f1d-2b020a84f9cd.png)

**Comment by Manuel83** [comment]
In version 2.1 the settings link is removed. Please clear the chrome browser cache
