### ISSUE TITLE
Contribution with files for controlling Hendi induction cocker

### ISSUE THREAD

**Issue by AHm74** [Manuel83/craftbeerpi#101]
Hi,

I have developed files to support the control of a Hendi induction cocker, do you want me to push the updates to the repository? Then I might need permission to push.

/Anders

**Comment by dguder** [comment]
Hi @AHm74 the usual way is to create a fork and then a feature branch where you can push your changes. At the end you can provide a pull request. You might check the guides at https://guides.github.com/

**Comment by AHm74** [comment]
I missed the fork step, I'll try again.
