### ISSUE TITLE
Version 2.2: Type in der Liste Steps wird nicht angezeigt

### ISSUE THREAD

**Issue by JamFfm** [Manuel83/craftbeerpi#108]
In der Brewing Ansicht werden in der Steps Ansicht vom Rezept nicht angezeigt ob es Automatische oder Manuelle Steps sind (Spalte Type)
http://hobbybrauer.de/forum/download/file.php?id=22466&mode=view

Total klasse Projekt. Und ich frei mich auf die Integration von iSpindel!!!

**Comment by Manuel83** [comment]
Ist ein Bug. Wird behoben.

**Comment by JamFfm** [comment]
Ist in der neuen Version behoben. Klasse ;-) Danke
