### ISSUE TITLE
How to implement changes to config.yaml

### ISSUE THREAD

**Issue by BoomerBrian** [Manuel83/craftbeerpi#119]
I am trying to change from Celsius to Fahrenheit. I have changed the config.yaml and restarted but nothing has happened. Is there something else that needs to be done for the changed to take affect?

**Comment by Manuel83** [comment]
When did you installed CraftBeerPi? There was a small issue with Fahrenheit but this is fixed since 4 days.

https://github.com/Manuel83/craftbeerpi/commit/9a342c92f7ead08eed081996f3a1d6e0b62e8f77

Regards,
Manuel

**Comment by BoomerBrian** [comment]
It is working now. Thanks.
