### ISSUE TITLE
Can not delete kettle when name is empty

### ISSUE THREAD

**Issue by Manuel83** [Manuel83/craftbeerpi#15]
Can not delete kettle when name is empty

**Comment by DaSchaef** [comment]
I can't reproduce this? (would be willing too help)

**Comment by danopat** [comment]
Same problem here using craftbeerpi 2.1. In GUI you have to click to the kettle name to delete it, when you create a kettle with no name, there is no text to click on so you can not edit/delete it.

**Comment by DaSchaef** [comment]
Hmm, I'm on 2.2 and I'm too stupid to create a kettle without name. The problem is that I can't create it, if the name is empty, ne kettle is not created - Manuel, did you already fix it?

**Comment by Manuel83** [comment]
This bug was fixed during refactoring of kettle dialogs for v2.1. 
In the past the "edit kettle dialog" was a separate screen. This separate screen had the bug. I think we can close this issue.
