### ISSUE TITLE
name thermometers

### ISSUE THREAD

**Issue by franktegtmeyer** [Manuel83/craftbeerpi#20]
add a function to rename thermometers in the "hardware" tab

**Comment by DaSchaef** [comment]
I'm not totally sure, but I think the name of the thermometer seems to be generated in the software/hw-driver layer (meaning e.g. the OneWire Bus Address).
What is the use case for a custom name? 
E.g. If I rename a thermometer to "Upper Thermoelement" in the "hardware" tab, then I still need to know what OneWire Bus Address it relates to (for correct HW connection)?

**Comment by Manuel83** [comment]
I don't understand the use case.

**Comment by DaSchaef** [comment]
No feedback :-(
I would vote for closing.

**Comment by franktegtmeyer** [comment]
When using more than one probe, I'd like to put a label on the cable and type in the name in the app. Would make it much more convienient than with the cryptic bus ids.... 😉 
Sorry... I'm on holiday right now.

**Comment by Manuel83** [comment]
Added to version 2.2
