### ISSUE TITLE
"Hide On Dashboard" Not Working

### ISSUE THREAD

**Issue by KenCope** [Manuel83/craftbeerpi#209]
Hi to all.  I think this has been asked before, but can't seem to find any answers out there.  The temp sensors, actors, etc. that I have "HIDE ON DASHBOARD" keep showing back up in the display after reboot.  The check box is still checked as hidden, but it is not hidden.  After unchecking, then rechecking, the item will hide.....until reboot.  Thanks to all. #

**Comment by DruBrewer** [comment]
I'm interested too

**Comment by Ins0x** [comment]
Facing the same issue
