### ISSUE TITLE
Web page audio alerts.

### ISSUE THREAD

**Issue by Dubzie** [Manuel83/craftbeerpi#218]
Can we have an option to upload a sound file, which the webpage will play when there is an alert.
I'd like the laptop that displays CBPi to do the alerting rather then having to wire in a buzzer.
Or both, so if i'm not within range of the buzzer i can hear it on a laptop or something like that.

**Comment by Dubzie** [comment]
Logging under CBPi3

**Comment by menschenpaste** [comment]
Did you found a way to use it?
