### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by henneonrails** [Manuel83/craftbeerpi#27]
![bildschirmfoto 2016-05-09 um 11 34 17](https://cloud.githubusercontent.com/assets/123651/15109189/70c06d84-15da-11e6-9249-a3e55dbefe9a.png)

I always get an error trying to donate your work. Would you please distribute a valid paypal email address, so one could send you some money.

regards Holger

**Comment by Manuel83** [comment]
Hi Holger,

if you use the donation button from the CraftBeerPI website (www.craftbeerpi.com) you should be redirected to the follwoing page. The correct email is manuel.fritsch@gmail.com

![image](https://cloud.githubusercontent.com/assets/5859486/15115841/305ee9c4-1601-11e6-9af9-3749696952b6.png)
