### ISSUE TITLE
Charting Python Bug in Dev2.2

### ISSUE THREAD

**Issue by DaSchaef** [Manuel83/craftbeerpi#31]
Hi Manuel,
https://github.com/Manuel83/craftbeerpi/blob/dev2.2/brewapp/base/kettle.py#L158

float(float())

sollte

float(format())

sein.
Bereite gerade das Brauen morgen vor, daher bin ich am falschen PC und kann kein Pull Request machen :/

Gruß Daniel

**Comment by Manuel83** [comment]
Kein thema. Ist gefixt!
