### ISSUE TITLE
GPIO27 ?

### ISSUE THREAD

**Issue by paalja** [Manuel83/craftbeerpi#40]
where did GPIO27 go?

**Comment by Manuel83** [comment]
In which version? 2.1 or 2.2?

**Comment by paalja** [comment]
version 2.1


![gpio27](https://cloud.githubusercontent.com/assets/19520617/15492109/19ffa0b0-2178-11e6-9778-1ccedc37b829.GIF)

http://www.datapels.com/GPIO27.GIF

**Comment by Manuel83** [comment]
Fixed in the master (v2.1)
