### ISSUE TITLE
add invert logic

### ISSUE THREAD

**Issue by paalja** [Manuel83/craftbeerpi#41]
...for ie relays...

**Comment by Manuel83** [comment]
Perfect that you added this feature request. The good news is that it is already under development.

**Comment by paalja** [comment]
good news to hear it is under development!

I found your CBP project yesterday and tested it right away, and for now,
it looks very promising!

At the moment I am building the hardware for a HERMS system, and done some
logic tests using StrangeBrew Elisnore but is buggy, crashes for time to
time and the project seems to be quite abandoned.

I am very glad if found your project! Keep up the good work!

best regards,
Paul

**Comment by Manuel83** [comment]
Available in dev2.2.
