### ISSUE TITLE
dev 2.2 - just background-image

### ISSUE THREAD

**Issue by tomandre76** [Manuel83/craftbeerpi#48]
Just getting the background-image in Safari on my Mac. Chrome and Firefox works fine. On my iPhone I also just get det background-image in Safari and also Chrome. This did work fine in 2.1

**Comment by henneonrails** [comment]
+1

Safari on iPhone only showing the background image. No dashboard or other interface.

![img_0384](https://cloud.githubusercontent.com/assets/123651/15799294/040099ac-2a58-11e6-9480-ea1e70d1e269.jpg)

**Comment by Manuel83** [comment]
Fixed this morning. Please do a `git pull `on dev2.2

**Comment by tomandre76** [comment]
How to do a git pull ?

**Comment by Manuel83** [comment]
Navigate into the CraftBeerPi installation folder and call "git pull"

**Comment by tomandre76** [comment]
Sorry Manuel, i´m not so into this Raspbian. Do you mean navigate in to the folder with Terminal on the Raspberry PI ? Or ? Can you please give me a more detailed explanation. From the noob :)

**Comment by Manuel83** [comment]
Open a terminal window on the RPi and navigate into the craftbeerpi installation folder. Default is /home/pi/craftbeerpi
Inside this folder call `git pull`

**Comment by tomandre76** [comment]
So I just write: git pull   in that folder ?

**Comment by tomandre76** [comment]
Had to write sudo git pull :)

**Comment by Manuel83** [comment]
Oh sorry :-)

**Comment by anthonyh1964** [comment]
Hi there, how do I install 2.2 version, I've tried downloading the zip file and scp to the craftbeerpi folder.

Cheers

Tony

**Comment by bjornarfonn** [comment]
Tony, navigate to your craftbeerpi folder and do: 
git checkout <branch> 
So for dev2.2 then do: git checkout dev2.2

**Comment by anthonyh1964** [comment]
Hi
So, I'm SSH into folder /home/pi/craftbeerpi and once in the folder I run the command sudo git checkout dev2.2

I get a "not a git repository" message

Cheers

**Comment by anthonyh1964** [comment]
OK I seem to be getting somewhere, but, the dashboard is blank

**Comment by anthonyh1964** [comment]
OK, the files seem to have updated, but, cannot run the session, the service does not appear to start, I've manually run sudo python runserver.py to start the service but, cannot access

**Comment by bjornarfonn** [comment]
Make sure when you are accessing the dashboard with a browser, that you are using "private mode" or "incognito" so that its not trying to display cached content. If you have tried to reboot the raspberry pi and still cant access it, you can easily run the installer again from the folder

**Comment by bjornarfonn** [comment]
Also, if the dashboard is not showing, try to run the setup again http://ip:5000/base/setup

**Comment by ivanbate** [comment]
hi there,
 i had the same issue when running "sudo git checkout dev2.2". It  updated
but I could not load the 2.2 app via web browser. I manually started the
server and that fails with an error msg. Screenshot attached with the
error. Something about the SwaggerAPI module!!

I just reinstalled 2.1 and that is now working again!!

**Comment by Manuel83** [comment]
I will have a look on this.
Sorry for this inconvenience
