### ISSUE TITLE
Unable to configure kettle agitator / heater with PiFace

### ISSUE THREAD

**Issue by chixxi** [Manuel83/craftbeerpi#51]
Wollte eigentlich Morgen mit der Version dev2.2 commit f61974e brauen und das wieder mal richtig testen. Leider ist es nicht möglich die PiFace Ausgänge in dem Setup der Kettles zu machen, es wird einfach keine Auswahl angeboten:

![screenshot2](https://cloud.githubusercontent.com/assets/1770007/15799183/f89f2708-2a53-11e6-8800-a0033936f620.png)

Interessanterweise klappt das aber einwandfrei bei der Ansteuerung der zusätzlichen Hardware:
![screenshot3](https://cloud.githubusercontent.com/assets/1770007/15799188/1be7212a-2a54-11e6-9b10-803ddbd82f6a.png)

Habe verschiedene Browser getestet und cache, cookies usw. gelöscht.

**Comment by Manuel83** [comment]
Hi 
in dev2.2 the concept changed a little bit. 
You have to configure your heater and agitator first in the hardware tab. After this you can select the configured hardware at the kettle setup.

Currently this may look complicated but it will change during further during the dev2.2 development.

**Comment by chixxi** [comment]
Thank you!

**Comment by Manuel83** [comment]
Let me know if its working

**Comment by chixxi** [comment]
Works just fine. Thank you for the fast response. I will send further feedback after brewing tomorrow.
