### ISSUE TITLE
SimpleFermentationLogic: add hysteresis

### ISSUE THREAD

**Issue by leckermojito** [Manuel83/craftbeerpi#57]
When using SimpleFermentationLogic the cooler is toggeling GPOI multiple times in less than a minute.
It would be usefull to get a little hysteresis build in to save the coolers live.

I´m no crack in python but i´ll try to get this solved using codesnippete from the overshoot logic.
As far as i can see you have already provided the basics with the "overshoot" variable

**Comment by Manuel83** [comment]
Thanks for providing the solution. I will add it to the code
