### ISSUE TITLE
push button shutdown of Pi

### ISSUE THREAD

**Issue by sittingaround** [Manuel83/craftbeerpi#59]
would be great if you could incorporate this into next build. Would make it so much easier to shutdown the brewery when your done. I know its only a couple lines of code so should be a quick addition.

**Comment by Manuel83** [comment]
Hi, a Shutdown Button is already available under the about tab.

**Comment by sittingaround** [comment]
its not currently working. it just restarts the Pi

**Comment by DaSchaef** [comment]
Yes, there seems to be a regression. It worked and during my last brew it didn't work anymore. If I've time, I'll take a look at it.
