### ISSUE TITLE
Uhrzeit

### ISSUE THREAD

**Issue by henneonrails** [Manuel83/craftbeerpi#6]
Es wäre schön, wenn bei den Zeiten die Systemzeit genommen würde. Im Moment sieht es mir so aus als würde hier die GMT benutzt.

**Comment by Manuel83** [comment]
Problem ist nachvollziehbar. Ich arbeite an einer Lösung

**Comment by Manuel83** [comment]
Intern werden die Zeiten in UTC gespeichert daher kommt das Problem.

**Comment by Manuel83** [comment]
Sollte jetzt im branch 2.1 gefixt sein. Bitte um Feedback

**Comment by henneonrails** [comment]
![bildschirmfoto 2016-04-22 um 23 53 30](https://cloud.githubusercontent.com/assets/123651/14756133/5c2189bc-08e7-11e6-9c73-4281dafa45c9.png)

ich habe mal ein Maischeprogramm per Hand durchgeklickt. Es sieht so aus als ob es noch nicht funktioniert. Alle Zeiten sind bei mir noch UTC obwohl der PI auf CEST eingestellt ist.

  ```
 pi@raspberrypi:~ $ date
 Fr 22. Apr 23:57:46 CEST 2016
```

**Comment by henneonrails** [comment]
oder muss ich die Datenbank wieder löschen?

**Comment by Manuel83** [comment]
Die Datenbank muss man nicht löschen. Ich schau noch mal drauf.

**Comment by chixxi** [comment]
Scheint in commit a9fbf99 auch noch fehlerhaft zu sein, 2 Stunden Offset.

Gruss chixxi

**Comment by Manuel83** [comment]
Das war echt doof. 
1. Python führt erstmal keine Timezone.
2. Beim speichern der Zeiten in der Datenbank wurde eine extra gesetzte Zeitzone abgeschnitten.

Bevor die Daten jetzt an den Browser übertragen werden, wird UTC als Zeitzone einfach fest angehängt. 
Im Browser wird dann auf die lokale Zeit umgerechnet. 

Bitte um Feedback ob es jetzt funktioniert.

**Comment by CK-AKS** [comment]
Soeben habe ich mal händisch ein Rezept mit angeschlossenem Temperaturfühler durchgespielt. Bei der ersten Rast (Einmaischen) wurde wiederum die Zeit um 2h zurückgesetzt, die folgenden Rasten haben sich dann wohl auf diese Anfangsstartzeit bezogen (sh. Screenshot: Bei der Gummirast im Rezept nimmt das Programm nicht die 45min, sondern 2:45h).
![screenshot_2016-04-26-13-36-56](https://cloud.githubusercontent.com/assets/18679330/14817323/d011ba5a-0bb6-11e6-9d2e-2d63fa2a4b1f.png)

**Comment by Manuel83** [comment]
Fixed
