### ISSUE TITLE
Temperature set to 0° after creating a new step

### ISSUE THREAD

**Issue by alientm** [Manuel83/craftbeerpi#68]
After creating a new step during a running process (in my case fermentation -  I want to add a additional step to increase the temp +1C° from 10C° to 11C° ) I created a new step with a new target temperature, go back to the dashboard, clicked the button to activate the next step and the target temperature was set to 0C° not the registered one.

After resetting the whole process and activating the steps all target temps works fine. The issue is reproducible.

...Alex

**Comment by Manuel83** [comment]
I added a 'reset current step' button to version 2.2.

![image](https://cloud.githubusercontent.com/assets/5859486/17648606/1bead70c-621c-11e6-9983-1528feb26112.png)
