### ISSUE TITLE
Number of steps limited to ten

### ISSUE THREAD

**Issue by chixxi** [Manuel83/craftbeerpi#7]
Die Anzahl der programmierbaren Schritte scheint aktuell auf 10 limitert zu sein. Da ich die Hopfengaben auch einprogrammiere wäre es gut wenn mehr möglich wären.

Versucht man einen 11. Schritt zu speichern verschwindet dieser ohne Warnung im Nirgendwo.

Könnte in dem Sinne auch ein Feature Request sein ;-)

**Comment by Manuel83** [comment]
Fixed with commit b727c7a
