### ISSUE TITLE
"SHUTDOWN CraftBeerPI" button don't seem to work

### ISSUE THREAD

**Issue by paalja** [Manuel83/craftbeerpi#73]
"SHUTDOWN CraftBeerPI" button don't seem to work

**Comment by Manuel83** [comment]
Which version? 2.1? 

Cheers 
Manuel

**Comment by paalja** [comment]
dev2.2 - I should have mentioned that initially
No log messages in app.log either

**Comment by Manuel83** [comment]
Shutdown is fixed, but I discovered that restart is also not working.
