### ISSUE TITLE
Connection of more than one 1wire sensor

### ISSUE THREAD

**Issue by olemde** [Manuel83/craftbeerpi#79]
Hi Manuel.
I cannot find a description how to connect more than one DS18B20 to the Pi. Is the 1-Wire function only listen to one GPIO? It means all other temperature probes has to be connected in DS18-bus?

thx for reply

Ole

**Comment by Manuel83** [comment]
Hi,

Have a Look here.
https://www.mkompf.com/weather/pionewiremini.html

Regards
Manuel
