### ISSUE TITLE
Delete single step

### ISSUE THREAD

**Issue by chixxi** [Manuel83/craftbeerpi#8]
Es ist nicht möglich einzelne Schritte komplett zu löschen.

Beispiel: Ich lade ein ganzes Rezept aus dem Rezeptbuch und möchte die Eiweissrast löschen. 

Ein Mülleimer-Sypbol unten in dem Feld wäre wünschenswert:
![screenshot1](https://cloud.githubusercontent.com/assets/1770007/14768349/2755d198-0a40-11e6-9053-6c073a3ca857.png)

**Comment by Manuel83** [comment]
Fixed with commit: b727c7a
