### ISSUE TITLE
Steps Tab

### ISSUE THREAD

**Issue by Mrpond1970** [Manuel83/craftbeerpi#92]
Hi,

Just updated today and no add steps tab showing.
![craftbeerpi_no_steps_tab](https://cloud.githubusercontent.com/assets/21977894/19022614/eeb4f6f8-88d3-11e6-9035-db5e02e62202.PNG)

**Comment by cocothenut** [comment]
Hi,

same error here
i had to clear the cache in the browser 
now it works

**Comment by Manuel83** [comment]
Hi,

I did a clean up of the user interface in version 2.2. Please clear the browser cache and try again.

Regards,
Manuel

**Comment by Mrpond1970** [comment]
Thanks Guys

It worked but CTRL + F5 was not enough using chrome had to go into chrome setting and do it that way.

All now working.

Cheers
